version: '3.9'

services:
  backend-app:
    build: .
    image: minas-app:1.0.0
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend:
    driver: overlay
    attachable: true